data_table_path: "plugins/MagicStone/data_table.xlsx"

worlds:
  - "shigen"

# データテーブルのうち、有効化対象のものを設定してください。
## データテーブルに無い物を指定しても無効となります。
max_fortune_level: 5

blocks:
  - "STONE"
  - "ANDESITE"
  - "DIORITE"
  - "GRANITE"
  - "TUFF"
  - "CALCITE"
  - "DEEPSLATE"

